name: Build and deploy to staging
on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dprothero/open5e-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Deploy to Digital Ocean
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          DIGITALOCEAN_APP_ID: 9478660a-dbcc-4c80-bcad-73d2c2152a40
        run: ./scripts/do_app_deploy.sh
